sudo: required
services:
  - docker

before_install:
  - docker build -t duydinh71/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run duydinh71/react-test npm test -- --coverage

after_success:
  - docker build -t duydinh71/multi-client ./client
  - docker build -t duydinh71/multi-nginx ./nginx
  - docker build -t duydinh71/multi-server ./server
  - docker build -t duydinh71/multi-worker ./worker

  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Take those images and push them to docker hub
  - docker push duydinh71/multi-client
  - docker push duydinh71/multi-nginx
  - docker push duydinh71/multi-server
  - docker push duydinh71/multi-worker    